_format_version: "2.1"
_transform: true

services:
  - name: postgrest
    url: http://postgrest:3000
    routes:
      - name: postgrest-route
        strip_path: false
        paths:
          - /rest/v1

  - name: gotrue
    url: http://gotrue:3100
    routes:
      - name: gotrue-route
        strip_path: false
        paths:
          - /auth/v1

  - name: studio
    url: http://studio:8000
    routes:
      - name: studio-route
        strip_path: false
        paths:
          - /

  - name: backend-api
    url: http://backend:3001
    routes:
      - name: backend-route
        strip_path: true
        paths:
          - /api

plugins:
  - name: request-transformer
    config:
      add:
        headers:
          - "Content-Type: application/json"
