-- Migration: Trial Management and Manual User Activation
-- Generated by opencode

-- 1. Create trial_history table for audit trail
CREATE TABLE IF NOT EXISTS trial_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  action TEXT NOT NULL CHECK (action IN ('created', 'extended', 'reduced', 'cancelled', 'expired', 'converted', 'activated', 'manual_create')),
  old_expiry TIMESTAMPTZ,
  new_expiry TIMESTAMPTZ,
  days_change INTEGER,
  changed_by UUID REFERENCES users(id),
  reason TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_trial_history_user ON trial_history(user_id);
CREATE INDEX IF NOT EXISTS idx_trial_history_created ON trial_history(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_trial_history_action ON trial_history(action);

-- 3. Enable RLS on trial_history
ALTER TABLE trial_history ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS policies for trial_history
-- Superadmin can view all trial history
CREATE POLICY "Superadmin view all trial history" ON trial_history
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM users
      WHERE users.id = auth.uid()
      AND users.role = 'superadmin'
    )
  );

-- System can insert trial history (via triggers)
CREATE POLICY "System insert trial history" ON trial_history
  FOR INSERT
  WITH CHECK (true);

-- 5. Add indexes to users table for trial queries
CREATE INDEX IF NOT EXISTS idx_users_is_trial ON users(is_trial_user) WHERE is_trial_user = true;
CREATE INDEX IF NOT EXISTS idx_users_trial_expires ON users(trial_expires_at);
CREATE INDEX IF NOT EXISTS idx_users_subscription ON users(subscription_plan);
CREATE INDEX IF NOT EXISTS idx_users_is_active ON users(is_active);

-- 6. Create function to calculate max trial extension (30 days total)
CREATE OR REPLACE FUNCTION get_max_trial_days()
RETURNS INTEGER AS $$
BEGIN
  RETURN 30;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 7. Create function to log trial history
CREATE OR REPLACE FUNCTION log_trial_history(
  p_user_id UUID,
  p_action TEXT,
  p_old_expiry TIMESTAMPTZ,
  p_new_expiry TIMESTAMPTZ,
  p_days_change INTEGER,
  p_changed_by UUID,
  p_reason TEXT,
  p_metadata JSONB DEFAULT '{}'
) RETURNS UUID AS $$
DECLARE
  v_log_id UUID;
BEGIN
  INSERT INTO trial_history (
    user_id,
    action,
    old_expiry,
    new_expiry,
    days_change,
    changed_by,
    reason,
    metadata
  ) VALUES (
    p_user_id,
    p_action,
    p_old_expiry,
    p_new_expiry,
    p_days_change,
    p_changed_by,
    p_reason,
    p_metadata
  ) RETURNING id INTO v_log_id;

  RETURN v_log_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 8. Create function to validate trial extension (max 30 days total)
CREATE OR REPLACE FUNCTION validate_trial_extension(
  p_user_id UUID,
  p_days_to_add INTEGER
) RETURNS BOOLEAN AS $$
DECLARE
  v_current_expiry TIMESTAMPTZ;
  v_new_expiry TIMESTAMPTZ;
  v_max_days INTEGER;
  v_total_trial_days INTEGER;
BEGIN
  -- Get current expiry
  SELECT trial_expires_at INTO v_current_expiry
  FROM users
  WHERE id = p_user_id;

  IF v_current_expiry IS NULL THEN
    RETURN FALSE;
  END IF;

  -- Get max trial days
  v_max_days := get_max_trial_days();

  -- Calculate total trial days from start
  SELECT
    EXTRACT(DAY FROM (v_current_expiry - trial_started_at))::INTEGER
  INTO v_total_trial_days
  FROM users
  WHERE id = p_user_id;

  -- Check if adding days would exceed max
  IF v_total_trial_days + p_days_to_add > v_max_days THEN
    RETURN FALSE;
  END IF;

  RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 9. Create function to extend trial
CREATE OR REPLACE FUNCTION extend_trial(
  p_user_id UUID,
  p_days INTEGER,
  p_changed_by UUID,
  p_reason TEXT
) RETURNS BOOLEAN AS $$
DECLARE
  v_old_expiry TIMESTAMPTZ;
  v_new_expiry TIMESTAMPTZ;
  v_success BOOLEAN;
BEGIN
  -- Validate extension
  SELECT validate_trial_extension(p_user_id, p_days) INTO v_success;
  IF NOT v_success THEN
    RETURN FALSE;
  END IF;

  -- Get current expiry
  SELECT trial_expires_at INTO v_old_expiry
  FROM users
  WHERE id = p_user_id;

  -- Calculate new expiry
  v_new_expiry := v_old_expiry + (p_days || ' days')::interval;

  -- Update user
  UPDATE users
  SET
    trial_expires_at = v_new_expiry,
    updated_at = NOW()
  WHERE id = p_user_id;

  -- Log history
  PERFORM log_trial_history(
    p_user_id,
    'extended',
    v_old_expiry,
    v_new_expiry,
    p_days,
    p_changed_by,
    p_reason
  );

  RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 10. Create function to reduce trial
CREATE OR REPLACE FUNCTION reduce_trial(
  p_user_id UUID,
  p_days INTEGER,
  p_changed_by UUID,
  p_reason TEXT
) RETURNS BOOLEAN AS $$
DECLARE
  v_old_expiry TIMESTAMPTZ;
  v_new_expiry TIMESTAMPTZ;
BEGIN
  -- Get current expiry
  SELECT trial_expires_at INTO v_old_expiry
  FROM users
  WHERE id = p_user_id;

  IF v_old_expiry IS NULL THEN
    RETURN FALSE;
  END IF;

  -- Calculate new expiry (can't go below current date)
  v_new_expiry := v_old_expiry - (p_days || ' days')::interval;

  IF v_new_expiry < NOW() THEN
    v_new_expiry := NOW();
  END IF;

  -- Update user
  UPDATE users
  SET
    trial_expires_at = v_new_expiry,
    updated_at = NOW()
  WHERE id = p_user_id;

  -- Log history
  PERFORM log_trial_history(
    p_user_id,
    'reduced',
    v_old_expiry,
    v_new_expiry,
    -p_days,
    p_changed_by,
    p_reason
  );

  RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 11. Create function to cancel trial
CREATE OR REPLACE FUNCTION cancel_trial(
  p_user_id UUID,
  p_changed_by UUID,
  p_reason TEXT
) RETURNS BOOLEAN AS $$
DECLARE
  v_old_expiry TIMESTAMPTZ;
BEGIN
  SELECT trial_expires_at INTO v_old_expiry
  FROM users
  WHERE id = p_user_id;

  IF v_old_expiry IS NULL THEN
    RETURN FALSE;
  END IF;

  -- Deactivate user
  UPDATE users
  SET
    is_active = false,
    updated_at = NOW()
  WHERE id = p_user_id;

  -- Log history
  PERFORM log_trial_history(
    p_user_id,
    'cancelled',
    v_old_expiry,
    NULL,
    NULL,
    p_changed_by,
    p_reason
  );

  RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 12. Create function to convert trial to paid
CREATE OR REPLACE FUNCTION convert_trial_to_paid(
  p_user_id UUID,
  p_plan TEXT,
  p_changed_by UUID,
  p_reason TEXT DEFAULT 'Converted to paid subscription'
) RETURNS BOOLEAN AS $$
DECLARE
  v_old_expiry TIMESTAMPTZ;
  v_old_plan TEXT;
BEGIN
  SELECT trial_expires_at, subscription_plan
  INTO v_old_expiry, v_old_plan
  FROM users
  WHERE id = p_user_id;

  IF v_old_expiry IS NULL THEN
    RETURN FALSE;
  END IF;

  -- Update user to paid
  UPDATE users
  SET
    is_trial_user = false,
    is_active = true,
    subscription_plan = p_plan,
    trial_expires_at = NULL,
    trial_started_at = NULL,
    updated_at = NOW()
  WHERE id = p_user_id;

  -- Log history
  PERFORM log_trial_history(
    p_user_id,
    'converted',
    v_old_expiry,
    NULL,
    NULL,
    p_changed_by,
    p_reason,
    jsonb_build_object('old_plan', v_old_plan, 'new_plan', p_plan)
  );

  RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 13. Create function to create paid user directly
CREATE OR REPLACE FUNCTION create_paid_user(
  p_email TEXT,
  p_password TEXT,
  p_name TEXT,
  p_store_name TEXT,
  p_role TEXT,
  p_plan TEXT,
  p_billing_cycle TEXT,
  p_payment_method TEXT,
  p_payment_reference TEXT,
  p_notes TEXT,
  p_changed_by UUID
) RETURNS UUID AS $$
DECLARE
  v_auth_id UUID;
  v_user_id UUID;
  v_tenant_id UUID;
BEGIN
  -- Create auth user
  INSERT INTO auth.users (email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data)
  VALUES (
    p_email,
    crypt(p_password, gen_salt('bf')),
    NOW(),
    jsonb_build_object('role', p_role, 'subscription_plan', p_plan),
    jsonb_build_object('name', p_name)
  )
  RETURNING id INTO v_auth_id;

  -- Create tenant for this user
  INSERT INTO stores (name, owner_id, created_at, updated_at)
  VALUES (p_store_name, v_auth_id, NOW(), NOW())
  RETURNING id INTO v_tenant_id;

  -- Update tenant_id to be the store id for single store
  UPDATE stores SET tenant_id = id WHERE id = v_tenant_id;

  -- Create user record
  INSERT INTO users (
    id,
    auth_id,
    email,
    name,
    role,
    tenant_id,
    store_id,
    subscription_plan,
    billing_cycle,
    is_active,
    is_trial_user,
    created_at,
    updated_at
  ) VALUES (
    v_auth_id,
    v_auth_id,
    p_email,
    p_name,
    p_role,
    v_tenant_id,
    v_tenant_id,
    p_plan,
    p_billing_cycle,
    true,
    false,
    NOW(),
    NOW()
  )
  RETURNING id INTO v_user_id;

  -- Log trial history for manual creation
  PERFORM log_trial_history(
    v_user_id,
    'manual_create',
    NULL,
    NULL,
    NULL,
    p_changed_by,
    p_notes,
    jsonb_build_object(
      'payment_method', p_payment_method,
      'payment_reference', p_payment_reference,
      'store_name', p_store_name
    )
  );

  RETURN v_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 14. Grant permissions
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT ON trial_history TO authenticated;
GRANT SELECT, INSERT ON trial_history TO authenticated;
GRANT EXECUTE ON FUNCTION get_max_trial_days() TO authenticated;
GRANT EXECUTE ON FUNCTION validate_trial_extension(UUID, INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION extend_trial(UUID, INTEGER, UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION reduce_trial(UUID, INTEGER, UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION cancel_trial(UUID, UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION convert_trial_to_paid(UUID, TEXT, UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION create_paid_user(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, UUID) TO authenticated;
